%
figure, plot3(POST(:,1),POST(:,2),-POST(:,3),'r',POSM(:,1),POSM(:,2),-POSM(:,3),'b')
figure, plot(TIME, X(:,1)-XHAT(:,1),'r', ...
    TIME,sqrt(PHAT(:,1)),'b',TIME,-sqrt(PHAT(:,1)),'b'),title('x1')
figure, plot(TIME, X(:,2)-XHAT(:,2),'r', ...
    TIME,sqrt(PHAT(:,2)),'b',TIME,-sqrt(PHAT(:,2)),'b'),title('x2')
figure, plot(TIME, X(:,3)-XHAT(:,3),'r', ...
    TIME,sqrt(PHAT(:,3)),'b',TIME,-sqrt(PHAT(:,3)),'b'),title('x3')
figure, plot(TIME, X(:,4)-XHAT(:,4),'r', ...
    TIME,sqrt(PHAT(:,4)),'b',TIME,-sqrt(PHAT(:,4)),'b'),title('x4')
figure, plot(TIME, X(:,5)-XHAT(:,5),'r', ...
    TIME,sqrt(PHAT(:,5)),'b',TIME,-sqrt(PHAT(:,5)),'b'),title('x5')
figure, plot(TIME, X(:,6)-XHAT(:,6),'r', ...
    TIME,sqrt(PHAT(:,6)),'b',TIME,-sqrt(PHAT(:,6)),'b'),title('x6')

figure, plot(TIME, sqrt((POST(:,1)-POSM(:,1)).^2+(POST(:,2)-POSM(:,2)).^2+(POST(:,3)-POSM(:,3)).^2),'r'),title('relative distance')

figure, plot(TIME, ACMD(:,1),'r', ...
    TIME,ACMD(:,2),'b',TIME,ACMD(:,3),'k'),title('command')

figure, plot(TIME, Z(:,1)-ZHAT(:,1),'r', ...
    TIME,sqrt(SBAR(:,1)),'b',TIME,-sqrt(SBAR(:,1)),'b'),title('r')
figure, plot(TIME, (Z(:,2)-ZHAT(:,2))*180/pi,'r', ...
    TIME,sqrt(SBAR(:,2))*180/pi,'b',TIME,-sqrt(SBAR(:,2))*180/pi,'b'),title('\theta_g')
figure, plot(TIME, (Z(:,3)-ZHAT(:,3))*180/pi,'r', ...
    TIME,sqrt(SBAR(:,2))*180/pi,'b',TIME,-sqrt(SBAR(:,2))*180/pi,'b'),title('\psi_g')